spring:
  application:
    name: reservation-system
  # DB 접속 설정
  datasource:
    # JDBC 드라이버 설정
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE

    # sql 접속 정보
    username: reservation_user
    password: res1234

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 단계: 엔티티 기반으로 테이블 자동 생성/수정
    show-sql: true # 실행되는 SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect # Oracle 방언 설정